//! This file should be autogenerated based on the headers created from the .edl file.
use enclave_contract_engine::external::ocalls::{
    ocall_allocate_qe, ocall_query_chain_qe, ocall_read_db_qe,
};
